### ISSUE TITLE
Stereo Camera Kit Availability

### ISSUE THREAD

**Issue by raghavkhanna** [ATLFlight/dfs-ros-example#3]
Is the stereo camera kit still available?
I did not find it on the Intrinsyc store.

**Comment by sgibsongithub** [comment]
Hi @raghavkhanna ,

Sorry for the delay! The stereo kits are now available: https://shop.intrinsyc.com/products/qualcomm-snapdragon-flight-stereovision-add-on-kit

Thanks,
Sarah
